### ISSUE TITLE
The current location is shown but there is no way to route from/to there.

### ISSUE THREAD

**Issue by xivk** [oSoc17/rideaway-frontend#1]
The current location is shown but there is no way to route from/to there. Expected is that the current location is either selected by default or that it can be selected somehow.

**Comment by ArnaudWeyts** [comment]
So I've spent some time trying to figure this one out, and sadly I couldn't find a native way for the mapbox-gl-geocoder to support geolocating the user. So I here's the plan:

- [X] Show my location option in the controls
- [X] Hide the option when starting to type
- [X] Show the option again when the input is empty
- [x] Set origin/destination on select
- [x] Calculate route
~~Hide my location option from other control when it's selected in one~~

## Complications
* Change the position when we move => recalculate every time => complicated
