### ISSUE TITLE
Selecting cycleroutes doesn't work when routing.

### ISSUE THREAD

**Issue by xivk** [oSoc17/rideaway-frontend#2]
Selecting cycleroutes doesn't work when a route is on the map. Expected would be to either remove the current route, show the cycleroute anyway or hide the route selection options.

**Comment by jbelien** [comment]
I do not agree with "_or hide the route selection options_".
It's necessary to be able to display a route on the map even when the routing result is displayed !

**Comment by ArnaudWeyts** [comment]
Fixed in 59bfd39, will need to add another filter option to hide all the routes.
