### ISSUE TITLE
Overlapping routes not showing any color

### ISSUE THREAD

**Issue by ArnaudWeyts** [oSoc17/rideaway-frontend#24]
When routes overlap, the color property returned in the GeoJSON is apparently a string with comma's. (etc `colour: 'red, green, blue'`, instead of `colour: 'red'`)

Mapbox can't interpret this.

I use this to color the lines:

`
 paint: {
          'line-color':
                  type: 'identity',
                  property: 'colour'
          }
}`

One solution would be to manually go through the GeoJSON and change the color but that would be really bad for performance.

For example green and orange overlap here, sometimes the routes overlap for a longer distance and then the color is just black 😭

![example](http://imgur.com/fNBX4Cr.png)

**Comment by jbelien** [comment]
Yes, that was my concern yesterday.

Could `paint.property` be a function ?

**Comment by ArnaudWeyts** [comment]
I'm afraid not...

**Comment by xivk** [comment]
My suggestion is to do some preprocessing on the GeoJSON response similar to what happens in navigation before handing it over to Mapbox GL.

Basically only change color when the color from the previous segment is not in the comma-separated list. For the first segment select the first color.

**Comment by jbelien** [comment]
Kudos to @TheOZoneBE if I understood correctly !!! :)

Can we close this issue ?

**Comment by theodedeken** [comment]
yes we can
