### ISSUE TITLE
Display information about route

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#5]
It could be nice to have more information by clicking on a route.

**Comment by ArnaudWeyts** [comment]
duplicate of #11

**Comment by jbelien** [comment]
No no, it is not a duplicate of #11 !
My idea was to add a function to have more information about the cycling network (not the route calculated).

**Comment by ArnaudWeyts** [comment]
Oh okay, my bad. Maybe a good idea to sum up what kind of information that would be.
