### ISSUE TITLE
Limit geocoding to Brussels

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#6]
**If possible**, could be nice to limit the geocoding result to Brussels.
It doesn't make any sense to go from Antwerpen to Arlon using this app.

**Comment by ArnaudWeyts** [comment]
Done in 1a24778

**Comment by jbelien** [comment]
I still can search (and have results) for "Kerkstraat, Adinkerke, 8660 West-Vlanderen, Belgium" (for instance).
It doesn't show the marker though. That's really a strange behavior.

**Comment by jbelien** [comment]
Sorry, I just saw all the changes are done in `develop` so I can't try it yet.

**Comment by ArnaudWeyts** [comment]
Yes I'll be pushing all the changes to the master branch tonight!
