### ISSUE TITLE
Orientation of the map could "follow" the direction of the user

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#7]
It could be nice that the map orientation follows the direction of the user ; that's usually easier to see where you are on a map.

**Comment by ArnaudWeyts** [comment]
Should this still be added to the route planner? I feel like it wouldn't be worth adding another button to be able to start/stop tracking the direction.

**Comment by jbelien** [comment]
You're right.
Doesn't make more sense anymore !
