### ISSUE TITLE
Display route instruction

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#8]
Display the result of routing calculation :

- Turn by turn 
- Color of the route to follow

**Comment by xivk** [comment]
Displaying the route instructions would be something specifically for navigation and are not usefull on an informational map, only during navigation.

**Comment by jbelien** [comment]
Yes, you're right, "turn by turn" is not a good idea.

But maybe display the list of routes/colors the user has to follow ?
Just to have a basic idea on the route to follow, if the user has a list of color (and maybe when to change color), he could write it on a piece of paper and use that while cycling.
